//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Control_InventarioAPI.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora_Productos
    {
        public int intBitacoraID { get; set; }
        public Nullable<int> intProductoID { get; set; }
        public Nullable<System.DateTime> datFechaBitacora { get; set; }
        public Nullable<int> intTipoProducto { get; set; }
        public string vchNombreProducto { get; set; }
        public Nullable<decimal> decPrecioProducto { get; set; }
        public Nullable<System.DateTime> datFechaAltaProducto { get; set; }
        public Nullable<int> intUsuarioAltaProducto { get; set; }
        public bool boolEstatusProducto { get; set; }
        public Nullable<int> intEventoID { get; set; }
    
        public virtual CAT_Eventos CAT_Eventos { get; set; }
        public virtual CAT_Productos CAT_Productos { get; set; }
    }
}
