//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Control_InventarioAPI.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_TipoProducto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAT_TipoProducto()
        {
            this.CAT_Productos = new HashSet<CAT_Productos>();
        }
    
        public int intTipoProductoID { get; set; }
        public string vchNombreTipoProducto { get; set; }
        public string vchDescripcionProducto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAT_Productos> CAT_Productos { get; set; }
    }
}
