//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Control_InventarioAPI.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAT_Usuarios()
        {
            this.CAT_Productos = new HashSet<CAT_Productos>();
        }
    
        public int intUsuarioID { get; set; }
        public string vchNombreUsuario { get; set; }
        public string vchApellidoUsuario { get; set; }
        public Nullable<System.DateTime> datFechaNacimientoUsuario { get; set; }
        public string vchTelefonoUsuario { get; set; }
        public bool boolEstatusUsuario { get; set; }
        public string vchUserUsuario { get; set; }
        public string vchPassUsuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAT_Productos> CAT_Productos { get; set; }
    }
}
